/* ===== Comodos, moveis e decoracoes ===== */
Object.assign(SPR, {
  /* --- SALA --- */
  cama_fosforo:[
  '.kkkkkkkkkkkkkkkkkkkkkkkk.',
  '.kwwwwwkbbbbbbbbbbbbbbbbk.',
  '.kwwwwwkbBbbBbbBbbBbbBbbk.',
  '.kwwwwwkbbbbbbbbbbbbbbbbk.',
  'kkkkkkkkkkkkkkkkkkkkkkkkkk',
  'k' + 'o'.repeat(24) + 'k',
  'koo' + 'R'.repeat(20) + 'ook',
  'k' + 'o'.repeat(24) + 'k',
  'kkkkkkkkkkkkkkkkkkkkkkkkkk'],
  cama_boneca:[
  '.kkkk.....................',
  '.knnk.....................',
  '.knnkkkkkkkkkkkkkkkkkkkkk.',
  '.knnkwwwwkrprprprprprprpk.',
  '.knnkwwwwkprprprprprprprk.',
  '.knnkkkkkkkkkkkkkkkkkkkkk.',
  '.knnnnnnnnnnnnnnnnnnnnnnk.',
  '.kNNNNNNNNNNNNNNNNNNNNNNk.',
  '.kkkk................kkkk.',
  '.knnk................knnk.',
  '.kkkk................kkkk.'],
  lum_abajur:[
  '....kkkk....',
  '...kppppk...',
  '..kppppppk..',
  '..kppppppk..',
  '.kppppppppk.',
  '.kppppppppk.',
  '.kkkkkkkkkk.',
  '.....kk.....',
  '.....kGk....',
  '.....kGk....',
  '.....kGk....',
  '.....kGk....',
  '.....kGk....',
  '....kkkkk...',
  '...kNNNNNk..',
  '..kNNNNNNNk.',
  '..kkkkkkkkk.'],
  sofa_esponja:[
  '.kkkkkkkkkkkkkkkkkkkkkk.',
  '.kEEEEEEEEEEEEEEEEEEEEk.',
  '.keeeeeeeeeeeeeeeeeeeek.',
  '.kkkkkkkkkkkkkkkkkkkkkk.',
  '.kyyyyyyyyyyyyyyyyyyyyk.',
  '.kyYyyyyYyyyyYyyyyyYyyk.',
  '.kyyyyyYyyyyyyyyYyyyyyk.',
  '.kyyyyyyyyyyyyyyyyyyyyk.',
  '.kkkkkkkkkkkkkkkkkkkkkk.'],
  sofa_mini:[
  '..kkkkkkkkkkkkkkkkkkkkkkk..',
  '..krrrrrrrrrrrrrrrrrrrrrk..',
  '..krrrrrrrrrrrrrrrrrrrrrk..',
  '.kkkkkkkkkkkkkkkkkkkkkkkkk.',
  '.krkRRRRRRRRRkRRRRRRRRRkrk.',
  '.krkRRRRRRRRRkRRRRRRRRRkrk.',
  '.kkkkkkkkkkkkkkkkkkkkkkkkk.',
  '..kk.....................kk'],
  tv_mini:[
  '....k......k......',
  '.....k....k.......',
  '......k..k........',
  '.kkkkkkkkkkkkkkkk.',
  '.kggggggggggggkgk.',
  '.kgkkkkkkkkkkgkrk.',
  '.kgkbbbbbbbbkgkgk.',
  '.kgkbbbwbbbbkgkgk.',
  '.kgkbbbbbbbbkgkgk.',
  '.kgkkkkkkkkkkgkkk.',
  '.kggggggggggggggk.',
  '.kkkkkkkkkkkkkkkk.',
  '...kk........kk...'],
  quadro:[
  'kkkkkkkkkkkk',
  'kNNNNNNNNNNk',
  'kNbbbbbbbbNk',
  'kNbbbyybbbNk',
  'kNbbbbbbbbNk',
  'kNeeeeeeeeNk',
  'kNeeeeeeeeNk',
  'kNNNNNNNNNNk',
  'kkkkkkkkkkkk'],
  /* --- COZINHA --- */
  mesa_madeira:[
  '.........kkkkkk.........',
  '........kwwyywwk........',
  '.........kkkkkk.........',
  'kkkkkkkkkkkkkkkkkkkkkkkk',
  'knnnnnnnnnnnnnnnnnnnnnnk',
  'kNnnnnnnnnnnnnnnnnnnnnNk',
  'kkkkkkkkkkkkkkkkkkkkkkkk',
  '.kNNk..............kNNk.',
  '.kNNk..............kNNk.',
  '.kNNk..............kNNk.',
  '.kkkk..............kkkk.'],
  gel_caixaleite:[
  '....kkkkkk....',
  '...kwwwwwwk...',
  '..kwwwwwwwwk..',
  '.kkkkkkkkkkkk.',
  '.kwwwwwwwwwwk.',
  '.kwwwwwwwwwwk.',
  '.kbbbbbbbbbbk.',
  '.kbbwwbbwwbbk.',
  '.kbbbbbbbbbbk.',
  '.kwwwwwwwwwwk.',
  '.kwwwwkkwwwwk.',
  '.kwwwwkkwwwwk.',
  '.kwwwwwwwwwwk.',
  '.kwwwwwwwwwwk.',
  '.kkkkkkkkkkkk.'],
  gel_mini:[
  '.kkkkkkkkkkkkkk.',
  '.kwwwwwwwwwwwwk.',
  '.kwwwwwwwwwwkwk.',
  '.kwwwwwwwwwwkwk.',
  '.kkkkkkkkkkkkkk.',
  '.kbbbbbbbbbbbbk.',
  '.kbbbbbbbbbbkbk.',
  '.kbbbbbbbbbbkbk.',
  '.kbbbbbbbbbbkbk.',
  '.kbbbbbbbbbbbbk.',
  '.kbbbbbbbbbbbbk.',
  '.kbbbbbbbbbbbbk.',
  '.kbbbbbbbbbbbbk.',
  '.kbbbbbbbbbbbbk.',
  '.kbbbbbbbbbbbbk.',
  '.kbbbbbbbbbbbbk.',
  '.kkkkkkkkkkkkkk.',
  '..kk........kk..'],
  fogao_lata:[
  '......kyk.......',
  '.....kyoyk......',
  '.....kyoyk......',
  '....kkkkkkk.....',
  '..kkkkkkkkkkk...',
  '.kgGGGGGGGGGgk..',
  '.kgggggggggggk..',
  '.kGgggggggggGk..',
  '.kgggggggggggk..',
  '.kGgggggggggGk..',
  '.kgggggggggggk..',
  '.kkkkkkkkkkkkk..'],
  fogao_mini:[
  '.kkkkkkkkkkkkkkkk.',
  '.kxxkkxxxxxkkxxxk.',
  '.kxxkkxxxxxkkxxxk.',
  '.kkkkkkkkkkkkkkkk.',
  '.kwwwwwwwwwwwwwwk.',
  '.kwrwrwwwwwwwwwwk.',
  '.kwwwwwwwwwwwwwwk.',
  '.kwkkkkkkkkkkkkwk.',
  '.kwkbbbbbbbbbbkwk.',
  '.kwkbbbbbbbbbbkwk.',
  '.kwkkkkkkkkkkkkwk.',
  '.kwwwwwwwwwwwwwwk.',
  '.kkkkkkkkkkkkkkkk.',
  '..kk..........kk..'],
  relogio:[
  '...kkkk...',
  '..kwwwwk..',
  '.kwwkwwwk.',
  '.kwwkwwwk.',
  '.kwwkkkwk.',
  '.kwwwwwwk.',
  '..kwwwwk..',
  '...kkkk...'],
  prateleira:[
  '..kkkk..kkkk..kkkk..',
  '..kyyk..kppk..keek..',
  '..kyyk..kppk..keek..',
  '..kkkk..kkkk..kkkk..',
  'kkkkkkkkkkkkkkkkkkkk',
  'kNNNNNNNNNNNNNNNNNNk',
  'kkkkkkkkkkkkkkkkkkkk'],
  /* --- BANHEIRO --- */
  banheira_lata:[
  '.kkkkkkkkkkkkkkkkkkkkkkkk.',
  '.kGbbbbbbbbbbbbbbbbbbbbGk.',
  '.kGbwbbbbbbbbbbbbbbbbbbGk.',
  '.kGGGGGGGGGGGGGGGGGGGGGGk.',
  '.kggggggggggggggggggggggk.',
  '.kGggggggggggggggggggggGk.',
  '.kkkkkkkkkkkkkkkkkkkkkkkk.'],
  banheira_porcelana:[
  '.kkkkkkkkkkkkkkkkkkkkkkkkkk.',
  'kwbbbbbbbbbbbbbbbbbbbbbbbbwk',
  'kwbwbbbbbbbbbbbbbbbbbbbbbbwk',
  'kwwwwwwwwwwwwwwwwwwwwwwwwwwk',
  'kwwwwwwwwwwwwwwwwwwwwwwwwwwk',
  'kwgwwwwwwwwwwwwwwwwwwwwwwgwk',
  '.kkkkkkkkkkkkkkkkkkkkkkkkkk.',
  '..kYk..................kYk..',
  '..kkk..................kkk..'],
  pia_tampinha:[
  '.....kkkk.....',
  '....kbbbbk....',
  '...kbwbbbbk...',
  '...kbbbbbbk...',
  '....kbbbbk....',
  '.....kkkk.....',
  '..............',
  '...kkkkkkkk...',
  '..krRrRrRrRk..',
  '..krrrrrrrrk..',
  '..kkkkkkkkkk..',
  '.....kkkk.....',
  '.....knnk.....',
  '.....knnk.....',
  '.....knnk.....',
  '....kkkkkk....',
  '...kNNNNNNk...',
  '...kkkkkkkk...'],
  pia_espelho:[
  '......kkkkkk......',
  '....kkggggggkk....',
  '...kggbbbbbbggk...',
  '..kggbbwbbbbbggk..',
  '..kggbbbbbbbbggk..',
  '..kggbbbbbbbbggk..',
  '...kggbbbbbbggk...',
  '....kkggggggkk....',
  '......kkkkkk......',
  '........kGk.......',
  '.kkkkkkkkkkkkkkkk.',
  '.kwwwwwwwwwwwwwwk.',
  '.kwkkkkkkkkkkkkwk.',
  '.kwkbbbbbbbbbbkwk.',
  '.kwwkkkkkkkkkkwwk.',
  '.kwwwwwwwwwwwwwwk.',
  '.kkkkkkkkkkkkkkkk.',
  '.kggggggkkggggggk.',
  '.kggggggkkggggggk.',
  '.kkkkkkkkkkkkkkkk.'],
  penico_dedal:[
  '...kkkk...',
  '..kggggk..',
  '.kgGgGgGk.',
  '.kgggggggk',
  '.kgGgGgGgk',
  '.kgggggggk',
  '.kgGgGgGgk',
  '.kkkkkkkkk'],
  privadinha:[
  '.kkkkkk.......',
  '.kwwwwk.......',
  '.kwwkwk.......',
  '.kwwwwk.......',
  '.kwwwwkkkkkkk.',
  '.kwwwkwwwwwwwk',
  '.kwwwkwbbbbbwk',
  '.kwwwkwwwwwwwk',
  '.kkkkkkkkkkkkk',
  '...kwwwwwwwk..',
  '...kwwwwwwwk..',
  '...kkkkkkkkk..'],
  patinho:[
  '..kkk...',
  '.kyykk..',
  '.kyykok.',
  '.kyyyk..',
  'kkyyyyk.',
  'kyyyyyyk',
  '.kkkkkk.'],
  toalha:[
  '...kk...',
  '...kk...',
  '.kkkkkk.',
  '.kppppk.',
  '.kppppk.',
  '.kwwwwk.',
  '.kppppk.',
  '.kppppk.',
  '.kwwwwk.',
  '.kppppk.',
  '.kppppk.',
  '.kkkkkk.'],
  seta:[
  '....k...',
  '...kk...',
  '..kwk...',
  '.kwwk...',
  '..kwk...',
  '...kk...',
  '....k...']
});
/* Comodos: cada um tem cor de parede/chao e 3 vagas de moveis. */
const ROOMS = [
  {id:'sala',     name:'Sala',     slots:['sofa', 'luminaria', 'cama']},
  {id:'cozinha',  name:'Cozinha',  slots:['geladeira', 'fogao', 'mesa']},
  {id:'banheiro', name:'Banheiro', slots:['banheira', 'pia', 'privada']}
];
/* Cada vaga: versao improvisada (gratis, nivel 0) e versao de verdade (nivel 1, paga).
   x = posicao relativa a largura da tela; dy = ajuste vertical sobre a linha do chao. */
const FURN = {
  sofa:      {room:'sala',     label:'Sofá',      x:0.03, tiers:[{name:'Sofá de esponja',          spr:'sofa_esponja',       bonus:''},
                                                                {name:'Sofá miniatura',            spr:'sofa_mini',          price:90,  bonus:'Carinho vale mais.'}]},
  luminaria: {room:'sala',     label:'Luminária', x:0.50, tiers:[{name:'Luminária de tampinha',    spr:'lampada',            bonus:''},
                                                                {name:'Abajur miniatura',          spr:'lum_abajur',         price:70,  bonus:'A toca fica mais bonita à noite.'}]},
  cama:      {room:'sala',     label:'Cama',      x:0.77, tiers:[{name:'Cama de caixa de fósforo', spr:'cama_fosforo',       bonus:''},
                                                                {name:'Cama de boneca',            spr:'cama_boneca',        price:130, bonus:'Dorme mais rápido.'}]},
  geladeira: {room:'cozinha',  label:'Geladeira', x:0.03, tiers:[{name:'Geladeira de caixa de leite', spr:'gel_caixaleite',  bonus:''},
                                                                {name:'Geladeira miniatura',       spr:'gel_mini',           price:110, bonus:'Comida na loja 1 moeda mais barata.'}]},
  fogao:     {room:'cozinha',  label:'Fogão',     x:0.28, tiers:[{name:'Fogãozinho de lata',       spr:'fogao_lata',         bonus:''},
                                                                {name:'Fogão miniatura',           spr:'fogao_mini',         price:100, bonus:'Sopa dá o dobro de energia.'}]},
  mesa:      {room:'cozinha',  label:'Mesa',      x:0.60, tiers:[{name:'Mesa de carretel',         spr:'carretel',           bonus:''},
                                                                {name:'Mesa de madeira',           spr:'mesa_madeira',       price:90,  bonus:'Cada refeição dá +5 de diversão.'}]},
  banheira:  {room:'banheiro', label:'Banheira',  x:0.03, tiers:[{name:'Banheira de lata de sardinha', spr:'banheira_lata',  bonus:''},
                                                                {name:'Banheira de porcelana',     spr:'banheira_porcelana', price:130, bonus:'Banho também dá +5 de diversão.'}]},
  pia:       {room:'banheiro', label:'Pia',       x:0.47, tiers:[{name:'Pia de tampinha',          spr:'pia_tampinha',       bonus:''},
                                                                {name:'Pia com espelho',           spr:'pia_espelho',        price:80,  bonus:'Higiene cai mais devagar.'}]},
  privada:   {room:'banheiro', label:'Privada',   x:0.78, tiers:[{name:'Penico de dedal',          spr:'penico_dedal',       bonus:''},
                                                                {name:'Privadinha de louça',       spr:'privadinha',         price:80,  bonus:'Ele faz cocô com menos frequência.'}]}
};
/* Decoracoes: compradas uma vez, aparecem no comodo. wall=true fica na parede (y relativo ao topo da parede). */
const DECOR = {
  tapete:         {room:'sala',     name:'Tapete de retalho',   price:25, kind:'rug'},
  poster:         {room:'sala',     name:'Pôster de queijo',    price:35, wall:true, x:0.08, y:8},
  quadro:         {room:'sala',     name:'Quadro pintado',      price:45, wall:true, x:0.72, y:10},
  planta:         {room:'sala',     name:'Planta no dedal',     price:30, x:0.86, floor:true},
  tv:             {room:'sala',     name:'TV miniatura',        price:120, x:0.20, floor:true, spr:'tv_mini'},
  roda:           {room:'sala',     name:'Rodinha de correr',   price:70, x:0.36, floor:true},
  papel_listras:  {room:'sala',     name:'Papel listrado',      price:60, kind:'paper'},
  papel_bolinhas: {room:'sala',     name:'Papel de bolinhas',   price:60, kind:'paper'},
  papel_coracoes: {room:'sala',     name:'Papel de corações',   price:80, kind:'paper'},
  relogio:        {room:'cozinha',  name:'Relógio de parede',   price:30, wall:true, x:0.78, y:6},
  prateleira:     {room:'cozinha',  name:'Prateleira de potes', price:50, wall:true, x:0.30, y:14},
  planta2:        {room:'cozinha',  name:'Plantinha na cozinha', price:30, x:0.86, floor:true, spr:'planta'},
  patinho:        {room:'banheiro', name:'Patinho de borracha', price:20, x:0.10, floor:true, dy:-12},
  toalha:         {room:'banheiro', name:'Toalha no gancho',    price:25, wall:true, x:0.70, y:12},
  tapete_banho:   {room:'banheiro', name:'Tapetinho do banho',  price:25, kind:'rug'},
  quadro2:        {room:'banheiro', name:'Quadro do mar',       price:45, wall:true, x:0.40, y:8, spr:'quadro'}
};
function furnTier(key){ return (S.furn && S.furn[key]) || 0; }
function furnSprite(key){ return FURN[key].tiers[furnTier(key)].spr; }
function hasUpgrade(key){ return furnTier(key) >= 1; }
